### ISSUE TITLE
VCF file not available in repository

### ISSUE THREAD

**Issue by xgao32** [shajoezhu/DEploid-Supplementary-Materials#1]
labMixedAfterFilter.vcf.gz is not found in this repository, please let me know if that vcf file is the same as labMixed.vcf.gz. Thanks.

**Comment by shajoezhu** [comment]
just uploaded @gaomrx

**Comment by xgao32** [comment]
Thanks, what about the other vcf files for figure 1 of the paper?

**Comment by shajoezhu** [comment]
if you are referring the panel, its

https://github.com/shajoezhu/DEploid-Supplementary-Materials/blob/master/labStrains.eg.panel.txt

**Comment by xgao32** [comment]
I am not sure how to see the connection between ```labStrains.eg.panel.txt``` and ```labStrains.eg.PLAF.txt``` with figure 1. What does the same row in both file mean in conjunction? 

```As validation we used a set of in vitro mixtures created by Wendler (2015) to simulate mixed infections. ```

Where can I find this set of data? Thanks.

**Comment by shajoezhu** [comment]
labMixedAfterFilter.vcf.gz is the file, and includes all lab mixtures made by Jason Wendler. For the whole genome, the data is available at ftp://ngs.sanger.ac.uk/production/pf3k/release_5/5.1/

labStrains.eg.PLAF.txt contains the PLAF of the lab mixtures, which is computed by alt/(ref+alt) at each row, alt and ref are the alternative and reference read counts of all lab samples 

HTH
Joe

**Comment by xgao32** [comment]
This helps a lot more. How can one figure out the proportion of each haplotype in labStrains.eg.PLAF.txt? My understanding is that the PLAF in this file refers to combining all PG3** and PG4** read counts in order to compute the PLAF. Thanks.

**Comment by shajoezhu** [comment]
Please see http://deploid.readthedocs.io/en/latest/ for more details
