### ISSUE TITLE
Missing Sample ID deploid.prop.4strains.csv

### ISSUE THREAD

**Issue by xgao32** [shajoezhu/DEploid-Supplementary-Materials#2]
Would appreciate knowing which rows match to which sample. Thanks.

**Comment by shajoezhu** [comment]
Dear @gaomrx 

Please see https://github.com/shajoezhu/DEploid-Supplementary-Materials/commit/ab35a49018919ed5c0cceac9fd3b513cfd873287

Best
Joe
