### ISSUE TITLE
Missing coil.k.txt

### ISSUE THREAD

**Issue by xgao32** [shajoezhu/DEploid-Supplementary-Materials#3]
Would appreciate having ```coil.k.txt``` to run ```plotK.r```. Thanks

**Comment by shajoezhu** [comment]
Dear @gaomrx 

Please follow https://github.com/shajoezhu/DEploid-Supplementary-Materials/tree/master/benchMark/COIL README

Best
Joe

**Comment by xgao32** [comment]
Hey Joe, I filed an [issue](https://github.com/kgalinsky/COIL/issues/2) as apparently the web version of COIL is having some problems. Please let me know if you know a workaround or can just provide the file ```coil.k.txt```. Thanks.

**Comment by shajoezhu** [comment]
Hey @gaomrx, I am not sure. I think they have developed new version, see at http://journals.plos.org/ploscompbiol/article/comments?id=10.1371/journal.pcbi.1005348

can you give this a try? I have not tried. So those results could differ

**Comment by xgao32** [comment]
I tried COIL and the updated version as well for a truncated subset of the original labMixedAfterFilter.vcf.gz data and it returns something. The 504 comes up when I try submitting all the [data](https://github.com/Greenhouse-Lab/THEREALMcCOIL/issues/5).
